"""A LiveKit voice interview agent.

Aria, the interviewer, greets the candidate and then walks through a set of
questions produced by the interview-planner service (the latest document in the
MongoDB ``voice_agent_planner`` collection; falls back to the bundled
``questions.json`` if the database is unreachable). After each answer she asks at
most ONE follow-up question --
but only for questions the planner scored highly (see FOLLOW_UP_THRESHOLD).
The follow-up is generated by judging the candidate's answer; that judgement is
used only to shape the follow-up and is not saved anywhere.

Pipeline:
  STT  -> Sarvam (saaras:v3)
  LLM  -> OpenAI (gpt-4o-mini)
  TTS  -> Sarvam (bulbul:v3, speaker "shubh")
  VAD  -> Silero
  Turn detection -> LiveKit multilingual model

Run it:
  uv run python agent.py download-files   # one-time: fetch VAD + turn-detector models
  uv run python agent.py console          # talk to it in your terminal (mic + speakers)
  uv run python agent.py dev              # connect to a LiveKit room (needs LIVEKIT_* env vars)
"""

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient
from openai import AsyncOpenAI

from livekit import agents
from livekit.agents import Agent, AgentSession, RoomInputOptions, StopResponse, llm
from livekit.plugins import openai, sarvam, silero
from livekit.plugins.turn_detector.multilingual import MultilingualModel

load_dotenv()

logger = logging.getLogger("interview-agent")

# Local fallback question set (used if the database is unreachable).
QUESTIONS_FILE = Path(__file__).parent / "questions.json"

# MongoDB: questions are generated by the interview-planner service and stored in
# the `voice_agent_planner` collection. The agent fetches the latest document at
# the start of every session, so new question sets are picked up with no redeploy.
DATABASE_URL = os.getenv("DATABASE_URL", "")
QUESTIONS_COLLECTION = "voice_agent_planner"
# Where the completed interview conversation (questions + answers) is saved.
CONVERSATION_COLLECTION = "vgi_conversation"

# Only questions the planner scored at or above this value earn a follow-up.
FOLLOW_UP_THRESHOLD = 0.85

INTERVIEWER_PERSONA = (
    "You are Aria, a warm and professional technical interviewer on a live voice call. "
    "You speak naturally and concisely, the way a real person would. Keep every reply "
    "short -- one or two sentences. Never lecture, never answer your own questions, and "
    "never read out scores or any internal notes."
)


def read_local_questions() -> list[dict]:
    """Fallback: read the question set bundled in questions.json."""
    return json.loads(QUESTIONS_FILE.read_text())["questions"]


async def fetch_latest_interview() -> dict:
    """Fetch the most recently created interview document from MongoDB."""
    client = AsyncIOMotorClient(DATABASE_URL, serverSelectionTimeoutMS=8000)
    try:
        collection = client.get_default_database()[QUESTIONS_COLLECTION]
        doc = await collection.find_one(sort=[("created_at", -1)])
    finally:
        client.close()
    if not doc:
        raise RuntimeError(f"no documents in '{QUESTIONS_COLLECTION}'")
    return doc


async def load_interview() -> tuple[list[dict], str | None, str | None]:
    """Resolve this session's questions plus the candidate's identifiers.

    Returns (questions, user_id, interview_id). user_id/interview_id are None when
    falling back to the local questions.json."""
    if DATABASE_URL:
        try:
            doc = await fetch_latest_interview()
            questions = doc["questions"]
            user_id = doc.get("user_id")
            interview_id = doc.get("interview_id")
            logger.info(
                "loaded %d questions from MongoDB (user_id=%s, interview_id=%s)",
                len(questions), user_id, interview_id,
            )
            return questions, user_id, interview_id
        except Exception as exc:
            logger.warning("MongoDB fetch failed (%s); falling back to questions.json", exc)
    return read_local_questions(), None, None


async def save_conversation(
    user_id: str | None, interview_id: str | None, conversation: list[dict]
) -> None:
    """Save the interview's question/answer conversation to MongoDB."""
    if not DATABASE_URL or not conversation:
        return
    doc = {
        "user_id": user_id,
        "interview_id": interview_id,
        "conversation": conversation,
        "created_at": datetime.now(timezone.utc),
    }
    client = AsyncIOMotorClient(DATABASE_URL, serverSelectionTimeoutMS=8000)
    try:
        await client.get_default_database()[CONVERSATION_COLLECTION].insert_one(doc)
        logger.info("saved conversation for user_id=%s (%d turns)", user_id, len(conversation))
    except Exception as exc:
        logger.warning("failed to save conversation (%s)", exc)
    finally:
        client.close()


class InterviewAgent(Agent):
    """An interviewer whose turns are driven explicitly by ``run_interview``.

    Every completed candidate turn is captured and handed to the driver via a
    queue, and the agent's automatic reply is suppressed -- so the driver has
    full control over what Aria says and when.
    """

    def __init__(self) -> None:
        super().__init__(instructions=INTERVIEWER_PERSONA)
        self._answers: asyncio.Queue[str] = asyncio.Queue()

    async def on_user_turn_completed(
        self, turn_ctx: llm.ChatContext, new_message: llm.ChatMessage
    ) -> None:
        # Hand the candidate's answer to the driver, then suppress the default
        # LLM reply -- the driver decides the next thing Aria says.
        await self._answers.put(new_message.text_content or "")
        raise StopResponse()

    async def next_answer(self) -> str:
        """Wait for the candidate to finish their next turn and return its text."""
        return await self._answers.get()

    def drain(self) -> None:
        """Discard any utterances captured so far (e.g. things said while Aria was
        still speaking, or a reply to the greeting) so they aren't mistaken for the
        answer to the next question."""
        while not self._answers.empty():
            self._answers.get_nowait()


class EndInterview(Exception):
    """Raised when the candidate asks to stop the interview early."""


_intent_client: AsyncOpenAI | None = None


def _get_intent_client() -> AsyncOpenAI:
    """Create the OpenAI client lazily so importing this module (e.g. at Docker
    build time, before secrets are injected) doesn't require OPENAI_API_KEY."""
    global _intent_client
    if _intent_client is None:
        _intent_client = AsyncOpenAI()  # uses OPENAI_API_KEY
    return _intent_client


VALID_INTENTS = {"end", "repeat", "hint", "simplify", "off_topic", "answer"}


async def detect_intent(question: str, answer: str) -> str:
    """Classify the candidate's turn into one of VALID_INTENTS."""
    try:
        resp = await _get_intent_client().chat.completions.create(
            model="gpt-4o-mini",
            temperature=0,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You classify an interview candidate's spoken turn. "
                        "Default to 'answer' -- only pick another label when the turn is "
                        "CLEARLY and entirely one of these. Reply with exactly ONE word:\n"
                        "- 'end' if they clearly want to stop, quit, or finish the interview now.\n"
                        "- 'repeat' if they explicitly ask to hear the same question again or "
                        "say they didn't catch it.\n"
                        "- 'hint' if they explicitly ask for a hint, a clue, or help getting started.\n"
                        "- 'simplify' if they explicitly ask you to rephrase or simplify the "
                        "question because they find it unclear.\n"
                        "- 'off_topic' ONLY if the WHOLE turn is clearly social and unrelated to "
                        "the question -- e.g. flirting, jokes, or chit-chat like 'I love you' or "
                        "'let's go for a walk'. A long, rambling, partial, uncertain, or "
                        "thinking-out-loud attempt, a tangent or example that still relates to the "
                        "topic, or simply 'I don't know' is NOT off_topic.\n"
                        "- 'answer' for everything else, including weak, incomplete, or "
                        "still-in-progress attempts to engage with the question.\n"
                        "When in doubt, choose 'answer'."
                    ),
                },
                {
                    "role": "user",
                    "content": f"Question: {question}\nCandidate said: {answer}",
                },
            ],
        )
        intent = (resp.choices[0].message.content or "").strip().lower()
    except Exception as exc:
        logger.warning("intent detection failed (%s); treating as a normal answer", exc)
        return "answer"
    return intent if intent in VALID_INTENTS else "answer"


async def speak(speech) -> None:
    """Wait for a queued utterance to finish playing before moving on."""
    await speech.wait_for_playout()


def speech_text(handle) -> str:
    """Extract the text Aria actually spoke from a SpeechHandle (e.g. an
    LLM-generated follow-up question), so it can be saved in the transcript."""
    parts = [
        item.text_content
        for item in handle.chat_items
        if getattr(item, "role", None) == "assistant" and item.text_content
    ]
    return " ".join(parts).strip()


async def get_answer(session: AgentSession, agent: InterviewAgent, question: str, reask) -> str:
    """Wait for a genuine answer to ``question``, handling these candidate intents:
      - 'end'       -> raise EndInterview (caller closes out)
      - 'hint'      -> give a small hint, then re-ask
      - 'simplify'  -> rephrase the question in plain words, then wait
      - 'repeat'    -> pose the question again
      - 'off_topic' -> gently redirect, then re-ask
      - 'answer'    -> return it

    ``reask`` is a no-arg coroutine factory that re-speaks the relevant question.
    """
    while True:
        agent.drain()  # discard stray utterances said while Aria was speaking
        answer = await agent.next_answer()
        intent = await detect_intent(question, answer)

        if intent == "answer":
            return answer
        if intent == "end":
            raise EndInterview()

        if intent == "hint":
            await speak(session.generate_reply(
                instructions=(
                    f'The candidate asked for a hint on this question: "{question}"\n'
                    "Give ONE short, encouraging hint that points them in the right "
                    "direction WITHOUT revealing the full answer, then invite them to try."
                )
            ))
        elif intent == "simplify":
            await speak(session.generate_reply(
                instructions=(
                    f'The candidate found this question unclear: "{question}"\n'
                    "Rephrase it in simpler, plain everyday language while keeping the same "
                    "meaning, then ask them that simpler version. Keep it to one or two "
                    "sentences."
                )
            ))
        else:  # 'repeat' or 'off_topic'
            if intent == "off_topic":
                await speak(session.say("Let's stay focused on the interview for now."))
            await reask()


async def end_interview(
    session: AgentSession, ctx: agents.JobContext, instructions: str
) -> None:
    """Speak a closing message, then quit the interview by disconnecting everyone.

    Called both when the candidate asks to quit and when all questions are done.
    """
    await speak(session.generate_reply(instructions=instructions))
    await asyncio.sleep(1.5)  # let the final words flush over the network
    await ctx.delete_room()   # ends the room for the candidate too (no-op in console)


async def run_interview(
    session: AgentSession, agent: InterviewAgent, ctx: agents.JobContext,
    questions: list[dict], user_id: str | None, interview_id: str | None,
) -> None:
    """Drive the interview: greet, ask each question in order (with at most one
    score-gated follow-up), record every question/answer pair, then quit. The
    candidate can ask for a hint, to have a question repeated or simplified, or to
    end the interview early at any point."""

    # Accumulated question/answer pairs, saved to MongoDB when the interview ends.
    conversation: list[dict] = []

    # 1. Greeting + explain the format.
    await speak(session.generate_reply(
        instructions=(
            "Start by clearly saying 'Hi, I am Aria' (say 'I am' in full, not 'I'm'), "
            "then warmly greet the candidate. In one or two short sentences, explain "
            "this is a short technical interview where you'll ask a series of questions "
            "they should answer out loud, then say you'll begin with the first question."
        )
    ))

    last_answer = ""

    try:
        # 2. Walk through the planned questions in order.
        for index, item in enumerate(questions):
            question = item["question"]
            score = item.get("score", 0.0)

            # Smooth transition acknowledging the previous answer (not before the first).
            if index > 0:
                await speak(session.generate_reply(
                    instructions=(
                        "In one short, warm sentence, acknowledge the candidate's previous "
                        f'answer ("{last_answer}") and signal you are moving on. '
                        "Do NOT ask a question."
                    )
                ))

            # Ask the planned question exactly as written.
            await speak(session.say(question))
            last_answer = await get_answer(
                session, agent, question,
                reask=lambda q=question: speak(session.say(q)),
            )
            conversation.append(
                {"type": "main", "question": question, "answer": last_answer}
            )

            # 3. One follow-up, only for high-scoring questions.
            if score >= FOLLOW_UP_THRESHOLD:
                followup = session.generate_reply(
                    instructions=(
                        f'The candidate was asked: "{question}"\n'
                        f'They answered: "{last_answer}"\n\n'
                        "Silently judge their answer, then ask exactly ONE concise follow-up "
                        "question that probes the most important gap or pushes them to go "
                        "deeper. Ask only that single question -- do not answer it, do not "
                        "stack multiple questions, and do not give feedback."
                    )
                )
                await speak(followup)
                followup_question = speech_text(followup)
                last_answer = await get_answer(
                    session, agent, question,
                    reask=lambda: speak(session.say(
                        "Could you share your answer to that follow-up?"
                    )),
                )
                conversation.append(
                    {"type": "followup", "question": followup_question, "answer": last_answer}
                )

        # 4a. All questions done -> save + quit.
        await save_conversation(user_id, interview_id, conversation)
        await end_interview(session, ctx, instructions=(
            "Warmly thank the candidate for their time, let them know the interview is "
            "complete, and wish them well. Keep it to one or two sentences."
        ))
    except EndInterview:
        # 4b. Candidate chose to stop early -> save what we have + quit gracefully.
        await save_conversation(user_id, interview_id, conversation)
        await end_interview(session, ctx, instructions=(
            "The candidate has asked to end the interview early. Warmly acknowledge "
            "that, thank them for their time, and wish them well. Keep it to one or "
            "two sentences and do NOT ask another question."
        ))


async def entrypoint(ctx: agents.JobContext):
    session = AgentSession(
        # Speech-to-text: Sarvam
        stt=sarvam.STT(language="en-IN", model="saaras:v3"),
        # Language model: OpenAI
        llm=openai.LLM(model="gpt-4o-mini"),
        # Text-to-speech: Sarvam
        tts=sarvam.TTS(
            target_language_code="en-IN", model="bulbul:v3", speaker="shubh"
        ),
        # Voice activity detection -- tuned to ignore background noise.
        #   activation_threshold: higher => needs more confident speech to trigger
        #     (0.5 default -> 0.6; push toward 0.7-0.8 in a noisy room).
        #   min_speech_duration: ignore brief blips (keystrokes, clicks, coughs).
        #   min_silence_duration: how long a pause must be before the turn ends.
        #     Raised to 1.2s so the candidate can pause to think mid-answer without
        #     being cut off (lower it toward 0.7 if Aria feels too slow to respond).
        vad=silero.VAD.load(
            activation_threshold=0.6,
            min_speech_duration=0.1,
            min_silence_duration=1.2,
        ),
        # Semantic turn detection (knows when the candidate is done speaking)
        turn_detection=MultilingualModel(),
    )

    agent = InterviewAgent()

    await session.start(
        room=ctx.room,
        agent=agent,
        room_input_options=RoomInputOptions(),
    )

    await ctx.connect()

    # Wait for the candidate to actually join before Aria greets them, so the
    # greeting isn't spoken to an empty room (which made it seem like the
    # candidate had to start the conversation).
    await ctx.wait_for_participant()

    # Fetch the latest question set (and the candidate's identifiers) from MongoDB.
    questions, user_id, interview_id = await load_interview()

    await run_interview(session, agent, ctx, questions, user_id, interview_id)


if __name__ == "__main__":
    agents.cli.run_app(agents.WorkerOptions(entrypoint_fnc=entrypoint))
